### ISSUE TITLE
My Modern Magnificent Modal Marvels

### ISSUE THREAD

**Issue by WaitingIdly** [IvarK/AntimatterDimensionsSourceCode#1539]
### **Is your feature request related to a problem? Please describe.**
Not everything has modals, and some still use `confirm()` calls. This issue aims to fix this by specifying what is lacking, and give a (rough) guide on what it should contain as a modal. Theory comes from #1144 
Most modals should include the ability to turn them off through that modal (exceptions would include but are not limited to the Companion glyph, Effarig, and Lai'tela)

### **The Modals are coming**
- [x] **Sacrifice**: Sacrifice is currently a confirm. I would suggest including the current formula, the current and next sacrifice multiplier, and what dimensions the sacrifice effects, and to what power (ie down at the bottom: `Infinity Dimension 3: x1e13`) (PR #1584)
- [x] **Eternity**: Eternity is currently a confirm. I would suggest including the EP gain from last time, being more expansive on what it initially resets, and gradually removing them as you get more milestones. It should also inform you what you start with, such as 2e25 IP after an achievement. (PR #1584)
- [x] **Edit Time Study Tree**: Already in-game as a modal, but needs improvement. Check #1547 (Fixed by PR #1733 -> which is now in PR #1736)
- [x] **Dilation**: Dilation is most currently a confirm. Entering should tell you at what EP you last did Dilation. Exiting should give you different things if you gained/didn't gain TP, and the later should tell you how to get TP.
- [x] **Reality**: Reality is already a confirm, mostly. When Realitying, you should be told what will reset (gradually decreasing as you gain perks), in addition to what you will start with (ie 2e3 EP), and what speed your achievements will be regained. Should not trigger while in a Celestial. Once you confirm, it should move you over to: (PR #1584)
- [x] **Glyph selection**: Currently a modal. This needs a cancel button, in addition to some work with how glyphs are displayed (not showing their sacrifice value, for instance). This should **not** be possible to turn off, although it should stop being called after the player has some Multiversal Alchemy. **NOTE**: IF YOU WOULD GAIN A GLYPH, AND HAVE NO EMPTY SPACE, THIS SHOULD HAVE ADDITIONAL TEXT WARNING YOU (and telling you what to do to fix it, ie reducing protected rows or sacrificing glyphs) (sort of done in PR #1584)
- [x] **Reset Reality**: Not in game. Just tell them it will reset all their progress in their current Reality, it just needs to be there, nothing special. Should probably make it a separate option from Reality, though.
- [x] **Glyph sacrifice/refine/delete**: Glyph sacrifice is already a confirm. Glyph refine is not in-game. This should tell you what you will do (sacrifice, refine, or delete) based on the glyph you are sacrificing. It should tell you the current value and amount gained when sacrificing, and include the resource cap when refining. Delete should have red text, you monster. Should also include a "you will sacrifice [x] glyphs" mode that triggers when Purging or Harsh Purging (PR #1736) (Harsh purge modal PR #1738)
- [x] **Companion Glyph sacrifice**: Currently, this is a sacrifice modal. The problem is that if you have confirm sac turned off it will just remove your glyph, sending you to hell forever, you monster. In addition, this does not trigger if you try to refine it. This should be separate, and always trigger in all conditions where you might remove it.
- [x] **Glyph replace**: Glyph replace is currently a confirm. Just tell it your reality will reset. (PR #1736)
- [x] **Glyph undo**: Glyph undo is currently a confirm. Honestly just needs to be a modal, the text absolutely fine. (PR #1736)
- [x] **HARD RESET**: Completely forgot about this one, but Hard Resetting should also be in modal form.
- [x] **Deleting Automator Script**: not surprised I completely missed this, but it should still be changed (consistency!)
### **And the stars guided me to safety**
- [x] **Celestials**: Current it does the Reset Reality confirm (eh????). Instead, it should tell the player the requirements of the celestial. Some celestials will require some special treatment (make sure not to trigger the on reset)
- [x] **Teresa exclusive**: Current glyph sacrifice multiplier from Teresa when entering. 
- [x] **Effarig exclusive**: Current level when entering.
- [x] **Enslaved exclusive**: Make it spooky, and tell the player about hints **I... can help... Let me... help...**
- [x] **V exclusive**: Include how many achievements you have, and what is required for the next level of those. Check that this works with hardV, without spoiling hardV in easyV.
- [x] **Ra exclusive**: I think this is the only one that doesn't need a special treatment? Neat
- [x] **Lai'tela exclusive**: Destabilize Lai'tela in less than 30s to increase the bonus significantly, but make Lai'tela much more difficult. Your best is [x]s (or "You haven't done this level of Lai'tela yet").
- [ ] **Pelle exclusive**: [redacted]

Exiting Celestials: (No confirmation, just a message)
- [x] **Exit Celestial**: Just a little blurb about how you gain nothing by exiting early. (PR #1736)
- [x] **Teresa exit**: On exit, if it increased tell them the former and later value, and how much it increased. Otherwise, warn them that it didn't increase. (PR #1738)
- [x] **Effarig exit**: Do not give them a confirmation for exiting, instead give them a modal telling them they have exited and what they gained.
- [x] **Enslaved exit**: N/A
- [x] **V exit**: N/A
- [x] **Ra exit**: N/A
- [x] **Lai'tela exit**: Tell them that Lai'tela has destabilized and the bonus to Dark Matter Dimensions is increased from x[value] to x[value].
- [ ] **Pelle exit**: [redacted]

### **Totally optional probably useless modals but it maybe makes sense**
- [x] **Dimension Boost**: Just telling you what it does directly. (PR #1738)
- [x] **Antimatter Galaxy**: Again, just telling you what it does directly. (PR #1738)
- [x] **Replicanti Galaxy**: Noticing a trend? Yeah. (PR #1738)
- [x] **Big Crunch**: Not until post-break, but post-eternity it just seems weird that eternity has it and big crunch doesn't. (PR #1738)
- [x] **Break Infinity**: Didn't agree with this at first, but changed my mind and added it.
- [x] **Import tree and Edit Time Study Tree**: Both already in-game as modals, but check the "alternative" for #1547 

Finally, some modals currently in game don't have the option to turn them off embed in them, mainly the challenges.
If this isn't possible, oops, sorry, ignore what I said earlier, but it seems like it should be.
Oh right also: try to keep it long form (ie Tachyon Particles not TP).

Anyways, thanks for reading my novella, and if you wouldn't mind rating it 5 stars?
