### ISSUE TITLE
How to Play checklist

### ISSUE THREAD

**Issue by earthernsence** [IvarK/AntimatterDimensionsSourceCode#606]
**Is your feature request related to a problem? Please describe.**
The how to play isn't super complete.

**Describe the solution you'd like**
me to get my ass off the couch and do shit

**Checklist**
High priority
- [x] Color the rarities and types
- [ ] Complete each tab for celestials (first 3 claimed by earth)

> - [x] Teresa
> - [x] Effarig
> - [x] The Enslaved Ones (note: mention reality is like a puzzle and that there are hints throughout)
> - [x] V
> - [x] Ra
> - [ ] Lai'tela
> - [ ] Pelle

- [x] Equipping/Sacrificing glyphs (i'll take care of it)
- [x] Glyph weights/Filtering (i don't understand any of this)

Low priority
- [x] Mention more caps
- [ ] Mention more hotkeys
- [x] Reference variables instead of hardcoding
- [x] Advanced mode explanation under Effarig's subtab
Comment more things to do
